### ISSUE TITLE
Flink Kafka Consumer throws Null Pointer Exception when consuming from Kafka topic

### ISSUE THREAD

**Issue by mrakshay** [dataArtisans/flink-training-exercises#12]
I am using this example Flink CEP where I am separating out the data as I have created one application which is Sending application to Kafka & another application reading from Kafka... I generated the producer for class TemperatureWarning i.e. in Kafka,I was sending data related to TemperatureWarning Following is my code which is consuming data from Kafka...

```
StreamExecutionEnvironment env=StreamExecutionEnvironment.getExecutionEnvironment();
env.setStreamTimeCharacteristic(TimeCharacteristic.EventTime);
env.enableCheckpointing(5000);
Properties properties=new Properties();
properties.setProperty("bootstrap.servers", "PUBLICDNS:9092");
properties.setProperty("zookeeper.connect", "PUBLICDNS:2181");
properties.setProperty("group.id", "test");

DataStream<TemperatureWarning> dstream=env.addSource(new FlinkKafkaConsumer09<TemperatureWarning>("MonitoringEvent", new MonitoringEventSchema(), properties));
  Pattern<TemperatureWarning, ?> alertPattern = Pattern.<TemperatureWarning>begin("first")
          .next("second")
          .within(Time.seconds(20));


  PatternStream<TemperatureWarning> alertPatternStream = CEP.pattern(
          dstream.keyBy("rackID"),
          alertPattern);
  DataStream<TemperatureAlert> alerts = alertPatternStream.flatSelect(
      (Map<String, TemperatureWarning> pattern, Collector<TemperatureAlert> out) -> {
          TemperatureWarning first = pattern.get("first");
          TemperatureWarning second = pattern.get("second");

          if (first.getAverageTemperature() < second.getAverageTemperature()) {
              out.collect(new TemperatureAlert(second.getRackID(),second.getAverageTemperature(),second.getTimeStamp()));
          }
      });
dstream.print();
alerts.print();
env.execute("Flink Kafka Consumer");
```

But when I execute this application,it throws following Exception:
` java.lang.NullPointerException
        at com.yash.source.MonitoringEventSchema.deserialize(MonitoringEventSchema.java:74)
        at com.yash.source.MonitoringEventSchema.deserialize(MonitoringEventSchema.java:1)
        at org.apache.flink.streaming.util.serialization.KeyedDeserializationSchemaWrapper.deserialize(KeyedDeserializationSchemaWrapper.java:39)
        at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumer09$ConsumerThread.run(FlinkKafkaConsumer09.java:466)`
Following is my code for **TemperatureWarning**

```
public class TemperatureWarning { 
public int rackID;
    public double averageTemperature;
    public long timeStamp;
    public TemperatureWarning(int rackID, double averageTemperature,long timeStamp) {
        this.rackID = rackID;
        this.averageTemperature = averageTemperature;
        this.timeStamp=timeStamp;
    }

    public TemperatureWarning() {
        this(-1, -1,-1);
    }

    public int getRackID() {
        return rackID;
    }

    public void setRackID(int rackID) {
        this.rackID = rackID;
    }

    public double getAverageTemperature() {
        return averageTemperature;
    }

    public void setAverageTemperature(double averageTemperature) {
        this.averageTemperature = averageTemperature;
    }
    public long getTimeStamp() {
		return timeStamp;
	}
	public void setTimeStamp(long timeStamp) {
		this.timeStamp = timeStamp;
	}
	@Override
    public boolean equals(Object obj) {
        if (obj instanceof TemperatureWarning) {
            TemperatureWarning other = (TemperatureWarning) obj;

            return rackID == other.rackID && averageTemperature == other.averageTemperature;
        } else {
            return false;
        }
    }
    @Override
    public int hashCode() {
        return 41 * rackID + Double.hashCode(averageTemperature);
    }
    @Override
    public String toString() {
       //return "TemperatureWarning(" + getRackID() + ", " + averageTemperature + ")";
    	String str=getRackID()+","+averageTemperature+","+getTimeStamp();
    	return str;
    	//return "TemperatureWarning(" + getRackID() +","+averageTemperature + ") "+ "," + getTimeStamp(); 
    }
}
```

Following is my code for **MonitoringEventSchema** : 

```
public class MonitoringEventSchema implements DeserializationSchema<TemperatureWarning>,SerializationSchema<TemperatureWarning>
{
	//@Override
	public TypeInformation<TemperatureWarning> getProducedType() {
		// TODO Auto-generated method stub
		return TypeExtractor.getForClass(TemperatureWarning.class);
	}
	//@Override
	public byte[] serialize(TemperatureWarning element) {
		// TODO Auto-generated method stub
		return element.toString().getBytes();
	}
	//@Override
	public TemperatureWarning deserialize(byte[] message) throws IOException {
		// TODO Auto-generated method stub
		TemperatureWarning warning=null;
		System.out.println("Before Encoded:"+message);
		if(message!=null)
		{
			String str=new String(message,"UTF-8");
			System.out.println("Message:"+str);
			String []value=str.split(",");
			warning.setRackID(Integer.parseInt(value[0]));
			warning.setAverageTemperature(Double.parseDouble(value[1]));
			warning.setTimeStamp(Long.parseLong(value[2]));
			return warning;
		}
		return null;
	}
	//@Override
	public boolean isEndOfStream(TemperatureWarning nextElement) {
		// TODO Auto-generated method stub
		return false;
	}
}
```

Can anyone please provide me the solution for this error ?? How can I solve this error ??

**Comment by aljoscha** [comment]
In you `deserialize` method you initialize `warning` with `null`. That's why a `NullPointerException` is thrown.

**Comment by mrakshay** [comment]
Thanks for the help ... I just want to confirm one thing....
Following is my code of Flink for consuming data from Kafka : 
        
  ```
       env.enableCheckpointing(5000);
	Properties properties=new Properties();
	properties.setProperty("bootstrap.servers", "54.175.124.192:9092");
	properties.setProperty("zookeeper.connect", "54.175.124.192:2181");
	properties.setProperty("group.id", "test");
	properties.setProperty("auto.offset.reset", "latest");
	DataStream<TemperatureWarning> dstream=env.addSource(new FlinkKafkaConsumer09<TemperatureWarning>("MonitoringEvent", new MonitoringEventSchema(), properties)).assignTimestampsAndWatermarks(new IngestionTimeExtractor<>());
```

I just want to know that I have set the **"auto.offset.reset"** property to **"latest"**...but it is printing the same message everytime...is the checkpointing occuring at Flink's side or Kafka side ?? How can I correct this mistake ??

**Comment by aljoscha** [comment]
Hmm, that's strange, the offsets should also be stored into Kafka. Could you try setting a different "group.id" and restart?
