### ISSUE TITLE
No data sinks have been created yet exception in PageRankWithEdgeWeights.scala

### ISSUE THREAD

**Issue by hulagu** [dataArtisans/flink-training-exercises#5]
After executing the example, an exception is thrown.
```
Exception in thread "main" java.lang.RuntimeException: No data sinks have been created yet. A program needs at least one sink that consumes data. Examples are writing the data set or printing it.
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:929)
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:908)
	at org.apache.flink.api.java.LocalEnvironment.execute(LocalEnvironment.java:81)
	at org.apache.flink.api.scala.ExecutionEnvironment.execute(ExecutionEnvironment.scala:627)
	at com.likya.flink.lectures.PageRankWithEdgeWeights$.main(PageRankWithEdgeWeights.scala:87)
	at com.likya.flink.lectures.PageRankWithEdgeWeights.main(PageRankWithEdgeWeights.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
There are lines comented may be related with the problem :

```
//Now run the Page Rank algorithm over the weighted graph
//val pageRanks = networkWithWeights.run[String](new PageRank[String, Double, Double, String](DAMPENING_FACTOR, maxIterations))
//pageRanks.writeAsCsv(outputPath, fieldDelimiter = "\t", lineDelimiter = "\n")

**Comment by fhueske** [comment]
Fixed

**Comment by azoz158** [comment]
how did you fix it?

**Comment by alpinegizmo** [comment]
See https://github.com/dataArtisans/flink-training-exercises/commit/bbbe1ec87d605dc52f47c8e599845fe252c99ab7
